name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  examples:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')

    runs-on: ubuntu-latest

    name: "Build examples"

    steps:
      - uses: actions/checkout@v1

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3
        with:
          version: '1.10.2'

      - name: Configure
        run: cmake -S examples -B build -G Ninja -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build
